/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaorderingsystem;

import pizzaorderingsystem.classes.Crust;
import pizzaorderingsystem.classes.Topping;
import pizzaorderingsystem.classes.Order;
import pizzaorderingsystem.classes.Sauce;
import pizzaorderingsystem.classes.Pizza;
import pizzaorderingsystem.classes.Size;
import java.util.ArrayList;

public class MainForm extends javax.swing.JFrame {

    private Pizza newPizza;
    private Pizza selectedPizza;
    private Order currentOrder;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        currentOrder = new Order();
        initComponents();
        setTitle("Pizza Ordering System - Order Summary");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPanel = new javax.swing.JPanel();
        jHomePanel = new javax.swing.JPanel();
        jNewPizzaBtn = new javax.swing.JButton();
        jEditPizzaBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jOrderSummaryTextArea = new javax.swing.JTextArea();
        jOrderTotalTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jNewPizzaPanel = new javax.swing.JPanel();
        jNewSizeComboBox = new javax.swing.JComboBox<>();
        jNewCrustComboBox = new javax.swing.JComboBox<>();
        jNewTopping1ComboBox = new javax.swing.JComboBox<>();
        jNewTopping2ComboBox = new javax.swing.JComboBox<>();
        jNewSauceComboBox = new javax.swing.JComboBox<>();
        jSizeLabel = new javax.swing.JLabel();
        jCrustLabel = new javax.swing.JLabel();
        jTopping1Label = new javax.swing.JLabel();
        jTopping2Label = new javax.swing.JLabel();
        jSauceLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jNewPizzaTextArea = new javax.swing.JTextArea();
        jAddToOrderBtn = new javax.swing.JButton();
        jNewPizzaTitleLabel = new javax.swing.JLabel();
        jNewPizzaDescriptionLabel = new javax.swing.JLabel();
        jEditPizzaPanel = new javax.swing.JPanel();
        jSelectedSizeComboBox = new javax.swing.JComboBox<>();
        jSelectedCrustComboBox = new javax.swing.JComboBox<>();
        jSelectedTopping1ComboBox = new javax.swing.JComboBox<>();
        jSelectedTopping2ComboBox = new javax.swing.JComboBox<>();
        jSelectedSauceComboBox = new javax.swing.JComboBox<>();
        jSizeLabel1 = new javax.swing.JLabel();
        jCrustLabel1 = new javax.swing.JLabel();
        jTopping1Label1 = new javax.swing.JLabel();
        jTopping2Label1 = new javax.swing.JLabel();
        jSauceLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jSelectedPizzaTextArea = new javax.swing.JTextArea();
        jUpdatePizzaBtn = new javax.swing.JButton();
        jDeletePizzaBtn = new javax.swing.JButton();
        jTraverseLeftBtn = new javax.swing.JButton();
        jTraverseRightBtn = new javax.swing.JButton();
        jTraversalComboBox = new javax.swing.JComboBox<>();
        jSelectedPizzaTitleLabel = new javax.swing.JLabel();
        jSelectedPizzaDescriptionLabel = new javax.swing.JLabel();
        jTopPanel = new javax.swing.JPanel();
        jHomeBtn = new javax.swing.JButton();
        jCloseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 25, 25));

        jMainPanel.setBackground(new java.awt.Color(55, 55, 55));
        jMainPanel.setLayout(new java.awt.CardLayout());

        jHomePanel.setBackground(new java.awt.Color(55, 55, 55));
        jHomePanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jHomePanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jNewPizzaBtn.setBackground(new java.awt.Color(220, 40, 40));
        jNewPizzaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNewPizzaBtn.setForeground(new java.awt.Color(255, 255, 255));
        jNewPizzaBtn.setText("New Pizza");
        jNewPizzaBtn.setToolTipText("Go to the New Pizza Form.");
        jNewPizzaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewPizzaBtnActionPerformed(evt);
            }
        });

        jEditPizzaBtn.setBackground(new java.awt.Color(220, 40, 40));
        jEditPizzaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEditPizzaBtn.setForeground(new java.awt.Color(255, 255, 255));
        jEditPizzaBtn.setText("Edit/Delete Pizza");
        jEditPizzaBtn.setToolTipText("Go to the Edit/Delete Pizza Form.");
        jEditPizzaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditPizzaBtnActionPerformed(evt);
            }
        });

        jOrderSummaryTextArea.setEditable(false);
        jOrderSummaryTextArea.setColumns(20);
        jOrderSummaryTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jOrderSummaryTextArea.setRows(5);
        jOrderSummaryTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        jOrderSummaryTextArea.setSelectionColor(new java.awt.Color(220, 40, 40));
        jScrollPane2.setViewportView(jOrderSummaryTextArea);

        jOrderTotalTextField.setEditable(false);
        jOrderTotalTextField.setBackground(new java.awt.Color(55, 55, 55));
        jOrderTotalTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jOrderTotalTextField.setForeground(new java.awt.Color(255, 255, 255));
        jOrderTotalTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jOrderTotalTextField.setText("£0.00");
        jOrderTotalTextField.setToolTipText("Total order cost in GBP.");
        jOrderTotalTextField.setAutoscrolls(false);
        jOrderTotalTextField.setBorder(null);
        jOrderTotalTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        jOrderTotalTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jOrderTotalTextField.setSelectionColor(new java.awt.Color(220, 40, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Order Cost");

        javax.swing.GroupLayout jHomePanelLayout = new javax.swing.GroupLayout(jHomePanel);
        jHomePanel.setLayout(jHomePanelLayout);
        jHomePanelLayout.setHorizontalGroup(
            jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jHomePanelLayout.createSequentialGroup()
                        .addGroup(jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNewPizzaBtn)
                            .addGroup(jHomePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jOrderTotalTextField)
                            .addComponent(jEditPizzaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jHomePanelLayout.setVerticalGroup(
            jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOrderTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditPizzaBtn)
                    .addComponent(jNewPizzaBtn))
                .addGap(12, 12, 12))
        );

        jMainPanel.add(jHomePanel, "jHomePanel");

        jNewPizzaPanel.setBackground(new java.awt.Color(55, 55, 55));
        jNewPizzaPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jNewPizzaPanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jNewSizeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNewSizeComboBox.setMaximumRowCount(10);
        jNewSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel(Size.values()));
        jNewSizeComboBox.setToolTipText("Select Size.");
        jNewSizeComboBox.setName(""); // NOI18N
        jNewSizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaComboBoxActionPerformed(evt);
            }
        });

        jNewCrustComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNewCrustComboBox.setModel(new javax.swing.DefaultComboBoxModel(Crust.values()));
        jNewCrustComboBox.setToolTipText("Select Crust.");
        jNewCrustComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaComboBoxActionPerformed(evt);
            }
        });

        jNewTopping1ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNewTopping1ComboBox.setMaximumRowCount(10);
        jNewTopping1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(Topping.values()));
        jNewTopping1ComboBox.setToolTipText("Select Topping 1 (Optional).");
        jNewTopping1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaComboBoxActionPerformed(evt);
            }
        });

        jNewTopping2ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNewTopping2ComboBox.setMaximumRowCount(10);
        jNewTopping2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(Topping.values()));
        jNewTopping2ComboBox.setToolTipText("Select Topping 2 (Optional).");
        jNewTopping2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaComboBoxActionPerformed(evt);
            }
        });

        jNewSauceComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNewSauceComboBox.setMaximumRowCount(10);
        jNewSauceComboBox.setModel(new javax.swing.DefaultComboBoxModel(Sauce.values()));
        jNewSauceComboBox.setToolTipText("Select Sauce.");
        jNewSauceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaComboBoxActionPerformed(evt);
            }
        });

        jSizeLabel.setBackground(new java.awt.Color(255, 255, 255));
        jSizeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        jSizeLabel.setText("SIZE");

        jCrustLabel.setBackground(new java.awt.Color(255, 255, 255));
        jCrustLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCrustLabel.setForeground(new java.awt.Color(255, 255, 255));
        jCrustLabel.setText("CRUST");

        jTopping1Label.setBackground(new java.awt.Color(255, 255, 255));
        jTopping1Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTopping1Label.setForeground(new java.awt.Color(255, 255, 255));
        jTopping1Label.setText("TOPPING 1");

        jTopping2Label.setBackground(new java.awt.Color(255, 255, 255));
        jTopping2Label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTopping2Label.setForeground(new java.awt.Color(255, 255, 255));
        jTopping2Label.setText("TOPPING 2");

        jSauceLabel.setBackground(new java.awt.Color(255, 255, 255));
        jSauceLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSauceLabel.setForeground(new java.awt.Color(255, 255, 255));
        jSauceLabel.setText("SAUCE");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jNewPizzaTextArea.setEditable(false);
        jNewPizzaTextArea.setColumns(20);
        jNewPizzaTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNewPizzaTextArea.setRows(5);
        jNewPizzaTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        jNewPizzaTextArea.setSelectionColor(new java.awt.Color(220, 40, 40));
        jScrollPane1.setViewportView(jNewPizzaTextArea);

        jAddToOrderBtn.setBackground(new java.awt.Color(220, 40, 40));
        jAddToOrderBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jAddToOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        jAddToOrderBtn.setText("Add to Order");
        jAddToOrderBtn.setToolTipText("Add the new pizza to the order.");
        jAddToOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddToOrderBtnActionPerformed(evt);
            }
        });

        jNewPizzaTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jNewPizzaTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        jNewPizzaTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jNewPizzaTitleLabel.setText("Add New Pizza");
        jNewPizzaTitleLabel.setToolTipText("");

        jNewPizzaDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNewPizzaDescriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        jNewPizzaDescriptionLabel.setText("<html>\n<p>To add a new pizza,</p>\n<p>please use the following combo boxes.</p>");

        javax.swing.GroupLayout jNewPizzaPanelLayout = new javax.swing.GroupLayout(jNewPizzaPanel);
        jNewPizzaPanel.setLayout(jNewPizzaPanelLayout);
        jNewPizzaPanelLayout.setHorizontalGroup(
            jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNewPizzaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNewPizzaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAddToOrderBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNewPizzaPanelLayout.createSequentialGroup()
                                .addGroup(jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSizeLabel)
                                    .addComponent(jCrustLabel)
                                    .addComponent(jTopping2Label)
                                    .addComponent(jSauceLabel)
                                    .addComponent(jTopping1Label))
                                .addGap(18, 18, 18)
                                .addGroup(jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNewCrustComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNewSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNewTopping1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNewTopping2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNewSauceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1)
                    .addGroup(jNewPizzaPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNewPizzaDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNewPizzaTitleLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jNewPizzaPanelLayout.setVerticalGroup(
            jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNewPizzaPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jNewPizzaTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNewPizzaDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSizeLabel))
                .addGap(18, 18, 18)
                .addGroup(jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewCrustComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCrustLabel))
                .addGap(18, 18, 18)
                .addGroup(jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewTopping1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTopping1Label))
                .addGap(18, 18, 18)
                .addGroup(jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewTopping2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTopping2Label))
                .addGap(18, 18, 18)
                .addGroup(jNewPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewSauceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSauceLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAddToOrderBtn)
                .addGap(12, 12, 12))
        );

        jNewSizeComboBox.getAccessibleContext().setAccessibleName("");

        jMainPanel.add(jNewPizzaPanel, "jAddPanel");
        jNewPizzaPanel.getAccessibleContext().setAccessibleName("");

        jEditPizzaPanel.setBackground(new java.awt.Color(55, 55, 55));
        jEditPizzaPanel.setPreferredSize(new java.awt.Dimension(424, 690));
        jEditPizzaPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jEditPizzaPanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jSelectedSizeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSelectedSizeComboBox.setMaximumRowCount(10);
        jSelectedSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel(Size.values()));
        jSelectedSizeComboBox.setToolTipText("Select Size.");
        jSelectedSizeComboBox.setName(""); // NOI18N
        jSelectedSizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaComboBoxActionPerformed(evt);
            }
        });

        jSelectedCrustComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSelectedCrustComboBox.setModel(new javax.swing.DefaultComboBoxModel(Crust.values()));
        jSelectedCrustComboBox.setToolTipText("Select Crust.");
        jSelectedCrustComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaComboBoxActionPerformed(evt);
            }
        });

        jSelectedTopping1ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSelectedTopping1ComboBox.setMaximumRowCount(10);
        jSelectedTopping1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(Topping.values()));
        jSelectedTopping1ComboBox.setToolTipText("Select Topping 1 (Optional).");
        jSelectedTopping1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaComboBoxActionPerformed(evt);
            }
        });

        jSelectedTopping2ComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSelectedTopping2ComboBox.setMaximumRowCount(10);
        jSelectedTopping2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(Topping.values()));
        jSelectedTopping2ComboBox.setToolTipText("Select Topping 2 (Optional).");
        jSelectedTopping2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaComboBoxActionPerformed(evt);
            }
        });

        jSelectedSauceComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSelectedSauceComboBox.setMaximumRowCount(10);
        jSelectedSauceComboBox.setModel(new javax.swing.DefaultComboBoxModel(Sauce.values()));
        jSelectedSauceComboBox.setToolTipText("Select Sauce.");
        jSelectedSauceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaComboBoxActionPerformed(evt);
            }
        });

        jSizeLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jSizeLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSizeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jSizeLabel1.setText("SIZE");

        jCrustLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jCrustLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCrustLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jCrustLabel1.setText("CRUST");

        jTopping1Label1.setBackground(new java.awt.Color(255, 255, 255));
        jTopping1Label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTopping1Label1.setForeground(new java.awt.Color(255, 255, 255));
        jTopping1Label1.setText("TOPPING 1");

        jTopping2Label1.setBackground(new java.awt.Color(255, 255, 255));
        jTopping2Label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTopping2Label1.setForeground(new java.awt.Color(255, 255, 255));
        jTopping2Label1.setText("TOPPING 2");

        jSauceLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jSauceLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSauceLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jSauceLabel1.setText("SAUCE");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jSelectedPizzaTextArea.setEditable(false);
        jSelectedPizzaTextArea.setColumns(20);
        jSelectedPizzaTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSelectedPizzaTextArea.setRows(5);
        jSelectedPizzaTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        jSelectedPizzaTextArea.setSelectionColor(new java.awt.Color(220, 40, 40));
        jScrollPane3.setViewportView(jSelectedPizzaTextArea);

        jUpdatePizzaBtn.setBackground(new java.awt.Color(220, 40, 40));
        jUpdatePizzaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jUpdatePizzaBtn.setForeground(new java.awt.Color(255, 255, 255));
        jUpdatePizzaBtn.setText("Ok");
        jUpdatePizzaBtn.setToolTipText("Update the selected pizza.");
        jUpdatePizzaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdatePizzaBtnActionPerformed(evt);
            }
        });

        jDeletePizzaBtn.setBackground(new java.awt.Color(220, 40, 40));
        jDeletePizzaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jDeletePizzaBtn.setForeground(new java.awt.Color(255, 255, 255));
        jDeletePizzaBtn.setText("Delete Pizza");
        jDeletePizzaBtn.setToolTipText("Remove the selected pizza from the order.");
        jDeletePizzaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeletePizzaBtnActionPerformed(evt);
            }
        });

        jTraverseLeftBtn.setBackground(new java.awt.Color(220, 40, 40));
        jTraverseLeftBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTraverseLeftBtn.setForeground(new java.awt.Color(255, 255, 255));
        jTraverseLeftBtn.setText("<");
        jTraverseLeftBtn.setToolTipText("Go to the previous pizza.");
        jTraverseLeftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTraverseLeftBtnActionPerformed(evt);
            }
        });

        jTraverseRightBtn.setBackground(new java.awt.Color(220, 40, 40));
        jTraverseRightBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTraverseRightBtn.setForeground(new java.awt.Color(255, 255, 255));
        jTraverseRightBtn.setText(">");
        jTraverseRightBtn.setToolTipText("Go the next pizza.");
        jTraverseRightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTraverseRightBtnActionPerformed(evt);
            }
        });

        jTraversalComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTraversalComboBox.setForeground(new java.awt.Color(255, 255, 255));
        jTraversalComboBox.setMaximumRowCount(10);
        jTraversalComboBox.setModel(new javax.swing.DefaultComboBoxModel(currentOrder.getPizzaIndexes().toArray()));
        jTraversalComboBox.setToolTipText("Go to a specific pizza (by index).");
        jTraversalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTraversalComboBoxActionPerformed(evt);
            }
        });

        jSelectedPizzaTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jSelectedPizzaTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        jSelectedPizzaTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jSelectedPizzaTitleLabel.setText("Select Pizza");

        jSelectedPizzaDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSelectedPizzaDescriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        jSelectedPizzaDescriptionLabel.setText("<html>\n<p>To either edit or delete a pizza, please use</p>\n<p>the following combo boxes and buttons.</p>");

        javax.swing.GroupLayout jEditPizzaPanelLayout = new javax.swing.GroupLayout(jEditPizzaPanel);
        jEditPizzaPanel.setLayout(jEditPizzaPanelLayout);
        jEditPizzaPanelLayout.setHorizontalGroup(
            jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditPizzaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEditPizzaPanelLayout.createSequentialGroup()
                        .addComponent(jTraverseLeftBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTraversalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTraverseRightBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSizeLabel1)
                            .addComponent(jCrustLabel1)
                            .addComponent(jTopping2Label1)
                            .addComponent(jSauceLabel1)
                            .addComponent(jTopping1Label1))
                        .addGap(18, 18, 18)
                        .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSelectedCrustComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSelectedSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSelectedTopping1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSelectedTopping2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSelectedSauceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditPizzaPanelLayout.createSequentialGroup()
                        .addComponent(jDeletePizzaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jUpdatePizzaBtn)))
                .addContainerGap())
            .addGroup(jEditPizzaPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSelectedPizzaDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSelectedPizzaTitleLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jEditPizzaPanelLayout.setVerticalGroup(
            jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditPizzaPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jSelectedPizzaTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSelectedPizzaDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTraverseLeftBtn)
                        .addComponent(jTraverseRightBtn)
                        .addComponent(jTraversalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jEditPizzaPanelLayout.createSequentialGroup()
                        .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSelectedSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSizeLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSelectedCrustComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCrustLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSelectedTopping1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTopping1Label1))
                        .addGap(18, 18, 18)
                        .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSelectedTopping2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTopping2Label1))
                        .addGap(18, 18, 18)
                        .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSelectedSauceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSauceLabel1))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jEditPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdatePizzaBtn)
                    .addComponent(jDeletePizzaBtn))
                .addGap(12, 12, 12))
        );

        jMainPanel.add(jEditPizzaPanel, "jEditPanel");
        jEditPizzaPanel.getAccessibleContext().setAccessibleName("");

        jTopPanel.setBackground(new java.awt.Color(100, 100, 100));

        jHomeBtn.setBackground(new java.awt.Color(220, 40, 40));
        jHomeBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jHomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        jHomeBtn.setText("Home/Order");
        jHomeBtn.setToolTipText("Go to the Home/Order Form.");
        jHomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jHomeBtn.setName(""); // NOI18N
        jHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHomeBtnActionPerformed(evt);
            }
        });

        jCloseBtn.setBackground(new java.awt.Color(220, 40, 40));
        jCloseBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCloseBtn.setForeground(new java.awt.Color(255, 255, 255));
        jCloseBtn.setText("Close");
        jCloseBtn.setToolTipText("Close the application.");
        jCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTopPanelLayout = new javax.swing.GroupLayout(jTopPanel);
        jTopPanel.setLayout(jTopPanelLayout);
        jTopPanelLayout.setHorizontalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHomeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCloseBtn)
                .addContainerGap())
        );
        jTopPanelLayout.setVerticalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHomeBtn)
                    .addComponent(jCloseBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHomeBtnActionPerformed
        switchPanel(jHomePanel);
    }//GEN-LAST:event_jHomeBtnActionPerformed

    private void jNewPizzaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewPizzaBtnActionPerformed
        switchPanel(jNewPizzaPanel);
    }//GEN-LAST:event_jNewPizzaBtnActionPerformed

    private void jEditPizzaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditPizzaBtnActionPerformed
        switchPanel(jEditPizzaPanel);
    }//GEN-LAST:event_jEditPizzaBtnActionPerformed

    private void jCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseBtnActionPerformed
        // Close the form (JFrame), stopping application processes
        System.exit(0);
    }//GEN-LAST:event_jCloseBtnActionPerformed

    private void jAddToOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddToOrderBtnActionPerformed
        currentOrder.addPizza(newPizza);
        switchPanel(jHomePanel);
    }//GEN-LAST:event_jAddToOrderBtnActionPerformed

    private void pizzaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaComboBoxActionPerformed
        Object srcInput = evt.getSource();

        // Set available choices depending on the panel shown
        if (jNewPizzaPanel.isShowing()) {
            setNewPizzaChoice(srcInput);
        } else if (jEditPizzaPanel.isShowing()) {
            setSelectedPizzaChoice(srcInput);
        }
    }//GEN-LAST:event_pizzaComboBoxActionPerformed

    private void jHomePanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jHomePanelAncestorAdded
        // Update order information and cost
        jOrderSummaryTextArea.setText(currentOrder.getOrderInformation());
        jOrderTotalTextField.setText(String.format(
                "£%.2f",
                currentOrder.calculateOrderCost()
        ));

        // Set the use of the edit button depending on the count of pizzas
        if (currentOrder.countPizzas() == 0) {
            jEditPizzaBtn.setEnabled(false);
        } else {
            jEditPizzaBtn.setEnabled(true);
        }
    }//GEN-LAST:event_jHomePanelAncestorAdded

    private void jNewPizzaPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jNewPizzaPanelAncestorAdded
        newPizza = new Pizza();
        setNewPizzaOptions();
    }//GEN-LAST:event_jNewPizzaPanelAncestorAdded

    private void jEditPizzaPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jEditPizzaPanelAncestorAdded
        // Select the options for the pizza added last by default
        selectedPizza = currentOrder.getPizza(currentOrder.countPizzas() - 1);
        setSelectedPizzaOptions();

        // Populate the traversal combo box with the indexes of pizzas
        jTraversalComboBox.setModel(new javax.swing.DefaultComboBoxModel(
                currentOrder.getPizzaIndexes().toArray()
        ));

        // Set the current index to that of the selected pizza
        jTraversalComboBox.setSelectedIndex(
                currentOrder.getPizzas().indexOf(selectedPizza)
        );

        // Set the use of the traversal inputs depending on the count of pizzas
        if (currentOrder.countPizzas() > 1) {
            jTraverseLeftBtn.setEnabled(true);
            jTraverseRightBtn.setEnabled(true);
            jTraversalComboBox.setEnabled(true);
        } else {
            jTraverseLeftBtn.setEnabled(false);
            jTraverseRightBtn.setEnabled(false);
            jTraversalComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_jEditPizzaPanelAncestorAdded

    private void jUpdatePizzaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdatePizzaBtnActionPerformed
        int selectedPizzaIndex = currentOrder.getPizzas().indexOf(selectedPizza);
        currentOrder.updatePizza(selectedPizzaIndex, selectedPizza);

        switchPanel(jHomePanel);
    }//GEN-LAST:event_jUpdatePizzaBtnActionPerformed

    private void jDeletePizzaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeletePizzaBtnActionPerformed
        int selectedPizzaIndex = currentOrder.getPizzas().indexOf(selectedPizza);
        currentOrder.deletePizza(selectedPizzaIndex);

        // Update the traversal combo box with the indexes of pizzas
        jTraversalComboBox.setModel(new javax.swing.DefaultComboBoxModel(
                currentOrder.getPizzaIndexes().toArray()
        ));

        switchPanel(jHomePanel);
    }//GEN-LAST:event_jDeletePizzaBtnActionPerformed

    private void jTraverseLeftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTraverseLeftBtnActionPerformed
        int selectedPizzaIndex = currentOrder.getPizzas().indexOf(selectedPizza);

        // Select either the previous index or the last index
        goToPizza(selectedPizzaIndex > 0
                ? selectedPizzaIndex - 1
                : currentOrder.countPizzas() - 1
        );
    }//GEN-LAST:event_jTraverseLeftBtnActionPerformed

    private void jTraverseRightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTraverseRightBtnActionPerformed
        int selectedPizzaIndex = currentOrder.getPizzas().indexOf(selectedPizza);

        // Select either the next index or the first index
        goToPizza(selectedPizzaIndex < currentOrder.countPizzas() - 1
                ? selectedPizzaIndex + 1
                : 0
        );
    }//GEN-LAST:event_jTraverseRightBtnActionPerformed

    private void jTraversalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTraversalComboBoxActionPerformed
        int selectedPizzaIndex = jTraversalComboBox.getSelectedIndex();
        goToPizza(selectedPizzaIndex);
    }//GEN-LAST:event_jTraversalComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddToOrderBtn;
    private javax.swing.JButton jCloseBtn;
    private javax.swing.JLabel jCrustLabel;
    private javax.swing.JLabel jCrustLabel1;
    private javax.swing.JButton jDeletePizzaBtn;
    private javax.swing.JButton jEditPizzaBtn;
    private javax.swing.JPanel jEditPizzaPanel;
    private javax.swing.JButton jHomeBtn;
    private javax.swing.JPanel jHomePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JComboBox<String> jNewCrustComboBox;
    private javax.swing.JButton jNewPizzaBtn;
    private javax.swing.JLabel jNewPizzaDescriptionLabel;
    private javax.swing.JPanel jNewPizzaPanel;
    private javax.swing.JTextArea jNewPizzaTextArea;
    private javax.swing.JLabel jNewPizzaTitleLabel;
    private javax.swing.JComboBox<String> jNewSauceComboBox;
    private javax.swing.JComboBox<String> jNewSizeComboBox;
    private javax.swing.JComboBox<String> jNewTopping1ComboBox;
    private javax.swing.JComboBox<String> jNewTopping2ComboBox;
    private javax.swing.JTextArea jOrderSummaryTextArea;
    private javax.swing.JTextField jOrderTotalTextField;
    private javax.swing.JLabel jSauceLabel;
    private javax.swing.JLabel jSauceLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jSelectedCrustComboBox;
    private javax.swing.JLabel jSelectedPizzaDescriptionLabel;
    private javax.swing.JTextArea jSelectedPizzaTextArea;
    private javax.swing.JLabel jSelectedPizzaTitleLabel;
    private javax.swing.JComboBox<String> jSelectedSauceComboBox;
    private javax.swing.JComboBox<String> jSelectedSizeComboBox;
    private javax.swing.JComboBox<String> jSelectedTopping1ComboBox;
    private javax.swing.JComboBox<String> jSelectedTopping2ComboBox;
    private javax.swing.JLabel jSizeLabel;
    private javax.swing.JLabel jSizeLabel1;
    private javax.swing.JPanel jTopPanel;
    private javax.swing.JLabel jTopping1Label;
    private javax.swing.JLabel jTopping1Label1;
    private javax.swing.JLabel jTopping2Label;
    private javax.swing.JLabel jTopping2Label1;
    private javax.swing.JComboBox<String> jTraversalComboBox;
    private javax.swing.JButton jTraverseLeftBtn;
    private javax.swing.JButton jTraverseRightBtn;
    private javax.swing.JButton jUpdatePizzaBtn;
    // End of variables declaration//GEN-END:variables

    /*
        Method to remove other components and show only chosen jPanels
     */
    private void switchPanel(javax.swing.JPanel chosenPanel) {
        // Remove other components and add just the chosen panel
        jMainPanel.removeAll();
        jMainPanel.add(chosenPanel);
        jMainPanel.repaint();
        jMainPanel.revalidate();

        // Set the window title based on the panel shown
        if (chosenPanel == jEditPizzaPanel) {
            setTitle("Pizza Ordering System - Edit/Delete Pizza");
        } else if (chosenPanel == jNewPizzaPanel) {
            setTitle("Pizza Ordering System - New Pizza");
        } else {
            setTitle("Pizza Ordering System - Order Summary");
        }
    }

    /*
        Method to traverse the order to retrieve a pizza at a given index
     */
    private void goToPizza(int targetPizzaIndex) {
        // Retrieve the pizza at a given index and update related elements
        if (currentOrder.countPizzas() > 0) {
            selectedPizza = currentOrder.getPizza(targetPizzaIndex);
            jTraversalComboBox.setSelectedIndex(targetPizzaIndex);
            jSelectedPizzaTextArea.setText(selectedPizza.getInformation());
            setSelectedPizzaOptions();
        }
    }

    /*
        Methods to update the choices displayed for the new or selected pizza
     */
    private void setNewPizzaChoice(Object srcInput) {
        // Check and update the corresponding pizza option
        if (srcInput == jNewSizeComboBox) {
            newPizza.setSize((Size) jNewSizeComboBox.getSelectedItem());
        } else if (srcInput == jNewCrustComboBox) {
            newPizza.setCrust((Crust) jNewCrustComboBox.getSelectedItem());
        } else if (srcInput == jNewTopping1ComboBox) {
            newPizza.setTopping1((Topping) jNewTopping1ComboBox.getSelectedItem());
        } else if (srcInput == jNewTopping2ComboBox) {
            newPizza.setTopping2((Topping) jNewTopping2ComboBox.getSelectedItem());
        } else {
            newPizza.setSauce((Sauce) jNewSauceComboBox.getSelectedItem());
        }

        // Update the main text area with current information
        jNewPizzaTextArea.setText(newPizza.getInformation());
    }

    private void setSelectedPizzaChoice(Object srcInput) {
        // Check and update the corresponding pizza option
        if (srcInput == jSelectedSizeComboBox) {
            selectedPizza.setSize((Size) jSelectedSizeComboBox.getSelectedItem());
        } else if (srcInput == jSelectedCrustComboBox) {
            selectedPizza.setCrust((Crust) jSelectedCrustComboBox.getSelectedItem());
        } else if (srcInput == jSelectedTopping1ComboBox) {
            selectedPizza.setTopping1((Topping) jSelectedTopping1ComboBox.getSelectedItem());
        } else if (srcInput == jSelectedTopping2ComboBox) {
            selectedPizza.setTopping2((Topping) jSelectedTopping2ComboBox.getSelectedItem());
        } else {
            selectedPizza.setSauce((Sauce) jSelectedSauceComboBox.getSelectedItem());
        }

        // Update the main text area with current information
        jSelectedPizzaTextArea.setText(selectedPizza.getInformation());
    }

    /*
        Methods to update all options for the new or selected pizza
     */
    private void setNewPizzaOptions() {
        // Set all selected options
        newPizza.setSize((Size) jNewSizeComboBox.getSelectedItem());
        newPizza.setCrust((Crust) jNewCrustComboBox.getSelectedItem());
        newPizza.setTopping1((Topping) jNewTopping1ComboBox.getSelectedItem());
        newPizza.setTopping2((Topping) jNewTopping2ComboBox.getSelectedItem());
        newPizza.setSauce((Sauce) jNewSauceComboBox.getSelectedItem());

        // Update the main text area with current information
        jNewPizzaTextArea.setText(newPizza.getInformation());
    }

    private void setSelectedPizzaOptions() {
        // Set all selected options
        jSelectedSizeComboBox.setSelectedItem(selectedPizza.getSize());
        jSelectedCrustComboBox.setSelectedItem(selectedPizza.getCrust());
        jSelectedTopping1ComboBox.setSelectedItem(selectedPizza.getTopping1());
        jSelectedTopping2ComboBox.setSelectedItem(selectedPizza.getTopping2());
        jSelectedSauceComboBox.setSelectedItem(selectedPizza.getSauce());

        // Update the main text area with current information
        jSelectedPizzaTextArea.setText(selectedPizza.getInformation());
    }
}
